namespace Kata.Logic;

// This code has been generated by JetBrains Rider.
public partial class Account
{
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((Account) obj);
    }

    public override int GetHashCode()
    {
        throw new System.NotImplementedException();
    }

    public static bool operator ==(Account left, Account right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(Account left, Account right)
    {
        return !Equals(left, right);
    }
}
